baseURL = "https://thefuture.build/"
languageCode = "en-us"
title = "Build the Future @ UC Berkeley"

disableHugoGeneratorInject = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
home = ["HTML","RSS"]


[menu]
  # Main Menu

  [[menu.main]]
      name = "Home"
      url = "/"
      weight = 0