baseURL = "https://thefuture.build/"
languageCode = "en-us"
title = "Build the Future"

disableHugoGeneratorInject = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
home = ["HTML","RSS"]


[menu]
  # Main Menu

  [[menu.main]]
      name = "Home"
      url = "/"
      weight = 1

  [[menu.main]]
      name = "About"
      url = "/about/"
      weight = 2

  [[menu.main]]
      name = "DeCal"
      url = "/decal/"
      weight = 3

  [[menu.main]]
      name = "Community"
      url = "/community/"
      weight = 4