baseURL = "https://thefuture.build/"
languageCode = "en-us"
title = "Build the Future"

disableHugoGeneratorInject = true
disableKinds = ["taxonomy", "taxonomyTerm"]

enableEmoji = true
enableRobotsTXT = true
canonifyURLs = true

[outputs]
home = ["HTML","RSS"]

[params]
description = "UC Berkeley’s student-run entrepreneurship hub."
banner = "/images/banner.png"

[menu]
  # Main Menu

  [[menu.main]]
      name = "Home"
      url = "/"
      weight = 1

  [[menu.main]]
      name = "Events"
      url = "/events/"
      weight = 2

  [[menu.main]]
      name = "About"
      url = "/about/"
      weight = 3

  [[menu.main]]
      name = "DeCal"
      url = "/decal/"
      weight = 4

  [[menu.main]]
      name = "Community"
      url = "/community/"
      weight = 5

  [[menu.main]]
      name = "Newsletters"
      url = "/newsletters/"
      weight = 6
