[build]
    functions = "functions/"

[context.production.environment]
  HUGO_VERSION = "0.82.0"
  
[context.deploy-preview.environment]
  HUGO_VERSION = "0.82.0"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.82.0"